---
deployment:
  tasks:
    # 1. Set environment variables for Composer
    - export COMPOSER_ALLOW_SUPERUSER=1

    # 2. Install Composer dependencies (optimized for production)
    - /opt/cpanel/composer/bin/composer install --no-dev --optimize-autoloader

    # 3. Set permissions (optional but recommended)
    - find storage -type d -exec chmod 775 {} \;
    - find bootstrap/cache -type d -exec chmod 775 {} \;

    # 4. Clear and cache Laravel config/routes/views
    - php artisan config:cache
    - php artisan route:cache
    - php artisan view:cache

    # 5. Run migrations (with --force to avoid confirmation prompt)
    - php artisan migrate --force
